/**
 * stfService.js - Lotus Agenda Structured Text File (STF) Parser & Serializer.
 * Handles import and export of Agenda's native data exchange format (.stf),
 * as well as JSON and Markdown exports.
 */

import { Item } from '../models/Item.js';
import { Category, CategoryValue } from '../models/Category.js';
import { formatLocalDate } from '../utils/dateUtils.js';

export class STFService {
  /**
   * Serialize an array of Items and Categories to Lotus Agenda STF format
   */
  static exportToSTF(items, categories = []) {
    let stf = '; Lotus Agenda Structured Text File (STF)\n';
    stf += '; Generated by AgendaVault (Lotus Agenda + nvALT)\n';
    stf += `; Export Date: ${new Date().toISOString()}\n\n`;

    // 1. Export Categories section
    stf += '\\Categories\\\n';
    categories.forEach(cat => {
      stf += `\\Cat\\${cat.name}\\Type\\${cat.type}\\\n`;
      cat.values.forEach(val => {
        const kwStr = val.keywords && val.keywords.length > 0 ? `\\Keywords\\${val.keywords.join(',')}` : '';
        stf += `  \\Val\\${val.name}${kwStr}\\\n`;
      });
    });
    stf += '\\EndCategories\\\n\n';

    // 2. Export Items section
    stf += '\\Items\\\n';
    items.forEach(item => {
      stf += '\\Item\\\n';
      stf += `${item.text}\n`;

      if (item.done) {
        stf += '\\Done\\1\\\n';
      }

      if (item.cost !== null && item.cost !== undefined) {
        stf += `\\Cost\\${item.cost}\\\n`;
      }

      // Categories and values
      Object.entries(item.categories || {}).forEach(([catName, val]) => {
        if (Array.isArray(val)) {
          val.forEach(v => {
            stf += `\\CatVal\\${catName}\\${v}\\\n`;
          });
        } else if (val !== null && val !== undefined && val !== '') {
          stf += `\\CatVal\\${catName}\\${val}\\\n`;
        }
      });

      // Attached Note
      if (item.note && item.note.trim()) {
        stf += '\\Note\\\n';
        stf += `${item.note}\n`;
        stf += '\\EndNote\\\n';
      }

      stf += '\\EndItem\\\n\n';
    });
    stf += '\\EndItems\\\n';

    return stf;
  }

  /**
   * Parse an STF format string into items and categories
   */
  static importFromSTF(stfContent) {
    const lines = stfContent.split(/\r?\n/);
    const importedItems = [];
    const importedCategories = new Map();

    let currentSection = null;
    let currentItem = null;
    let currentNote = [];
    let readingNote = false;
    let currentCat = null;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();

      // Skip comments
      if (trimmed.startsWith(';')) continue;

      if (trimmed === '\\Categories\\') {
        currentSection = 'categories';
        continue;
      }
      if (trimmed === '\\EndCategories\\') {
        currentSection = null;
        continue;
      }
      if (trimmed === '\\Items\\') {
        currentSection = 'items';
        continue;
      }
      if (trimmed === '\\EndItems\\') {
        currentSection = null;
        continue;
      }

      // Reading Categories
      if (currentSection === 'categories') {
        if (trimmed.startsWith('\\Cat\\')) {
          const parts = trimmed.split('\\').filter(Boolean);
          // \Cat\Name\Type\text\
          const catName = parts[1];
          const type = parts[3] || 'text';
          currentCat = new Category({ name: catName, type });
          importedCategories.set(catName, currentCat);
        } else if (trimmed.startsWith('\\Val\\') && currentCat) {
          const parts = trimmed.split('\\').filter(Boolean);
          const valName = parts[1];
          let keywords = [];
          const kwIndex = parts.indexOf('Keywords');
          if (kwIndex !== -1 && parts[kwIndex + 1]) {
            keywords = parts[kwIndex + 1].split(',');
          }
          currentCat.addValue(new CategoryValue({ name: valName, keywords }));
        }
        continue;
      }

      // Reading Items
      if (currentSection === 'items' || currentItem) {
        if (readingNote) {
          if (trimmed === '\\EndNote\\') {
            readingNote = false;
            if (currentItem) {
              currentItem.note = currentNote.join('\n').trim();
            }
            currentNote = [];
          } else {
            currentNote.push(line);
          }
          continue;
        }

        if (trimmed === '\\Item\\') {
          currentItem = new Item();
          continue;
        }

        if (trimmed === '\\EndItem\\') {
          if (currentItem && currentItem.text) {
            importedItems.push(currentItem);
          }
          currentItem = null;
          continue;
        }

        if (trimmed === '\\Note\\') {
          readingNote = true;
          currentNote = [];
          continue;
        }

        if (trimmed.startsWith('\\Done\\')) {
          if (currentItem) {
            currentItem.done = true;
            if (!currentItem.categories['Done']) {
              currentItem.categories['Done'] = formatLocalDate(new Date());
            }
            if (!currentItem.categories['Status']) {
              currentItem.categories['Status'] = 'Done';
            }
          }
          continue;
        }

        if (trimmed.startsWith('\\Cost\\')) {
          const parts = trimmed.split('\\').filter(Boolean);
          if (currentItem && parts[1]) currentItem.cost = parseFloat(parts[1]);
          continue;
        }

        if (trimmed.startsWith('\\CatVal\\')) {
          const parts = trimmed.split('\\').filter(Boolean);
          if (currentItem && parts.length >= 3) {
            const catName = parts[1];
            const catVal = parts.slice(2).join('\\'); // Support values with slashes
            const isMulti = catName === 'People' || catName === 'Tags' || (importedCategories.get(catName)?.type === 'multi');
            const existing = currentItem.categories[catName];

            if (isMulti) {
              if (!existing) {
                currentItem.categories[catName] = [catVal];
              } else if (Array.isArray(existing)) {
                if (!existing.includes(catVal)) existing.push(catVal);
              } else {
                currentItem.categories[catName] = existing === catVal ? [existing] : [existing, catVal];
              }
            } else {
              if (!existing) {
                currentItem.categories[catName] = catVal;
              } else if (Array.isArray(existing)) {
                if (!existing.includes(catVal)) existing.push(catVal);
              } else {
                if (existing !== catVal) currentItem.categories[catName] = [existing, catVal];
              }
            }
          }
          continue;
        }

        // If line is not a tag, it is the item text (supports multi-line wrapped headlines)
        if (currentItem && trimmed && !trimmed.startsWith('\\')) {
          if (!currentItem.text) {
            currentItem.text = trimmed;
          } else {
            currentItem.text += ' ' + trimmed;
          }
        }
      }
    }

    return {
      items: importedItems,
      categories: Array.from(importedCategories.values())
    };
  }

  /**
   * Export all data to clean modern JSON
   */
  static exportToJSON(data) {
    return JSON.stringify(data, null, 2);
  }

  /**
   * Import data from JSON
   */
  static importFromJSON(jsonString) {
    return JSON.parse(jsonString);
  }

  /**
   * Export all items as a combined Markdown document
   */
  static exportToMarkdown(items) {
    let md = '# AgendaVault Notes & Items\n\n';
    items.forEach(item => {
      const checkbox = item.done ? '[x]' : '[ ]';
      md += `## ${checkbox} ${item.text}\n\n`;

      const meta = [];
      Object.entries(item.categories || {}).forEach(([cat, val]) => {
        meta.push(`**${cat}**: ${Array.isArray(val) ? val.join(', ') : val}`);
      });
      if (meta.length > 0) {
        md += `> ${meta.join(' | ')}\n\n`;
      }

      if (item.note) {
        md += `${item.note}\n\n`;
      }
      md += '---\n\n';
    });
    return md;
  }
}
